config/routes.rb
Rails.application.routes.draw do

    devise_scope :admin do
      get "/sign_out" => "devise/sessions#destroy"
      root to: "devise/sessions#new"
    end

    devise_for :admins, path: '/'

  resources  :home
  get 'view' => 'home#view'
  get 'search' => 'home#search'
  get 'return_due' => 'home#return_due'

   

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable

         validates_strength_of :password, :with => :email

end

app/models/book.rb
class Book < ActiveRecord::Base
   
	     validates:firstname , presence:true,
         length: { minimum: 2 }

         validates:lastname , presence:true,
         length: { minimum: 2 }

		 validates:reg_number , presence:true,
         length: { minimum: 11 },
         numericality:{only_integer:true}         

         validates:phone , presence:true,
         numericality:{only_integer:true}


       validates:gender , presence:true

	 	 validates:category , presence:true,
       length: { minimum: 2 }


	 	 validates:author , presence:true,
         length: { minimum: 2 }


	 	 validates:title , presence:true,
         length: { minimum: 2 }

         #scope :in_last_month , -> {where("created_at.strftime('%Y %m %d') ?", 1.month.ago.strftime('%Y-%m-%d'))}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
  add_flash_types :successful,:empty_search


	  def after_sign_in_path_for(resource_or_scope)
		new_home_path  	
	  end


	 def after_sign_out_path_for(resource_or_scope)
		new_admin_session_path
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_admin!

  def index
  end

  def search
    if params[:search].blank? 
      flash[:empty_search]= "can't be blank"
      redirect_to new_home_path
    else

      @search_result = Book.where("reg_number LIKE '%#{params[:search]}%' or firstname LIKE '%#{params[:search]}%' 
        or lastname LIKE '%#{params[:search]}%' ").order("id DESC").page(params[:page]).per_page(10)      
    end 
  end

  def view
    sleep 2
    @books = Book.all.order("id DESC").page(params[:page]).per_page(1) 
  
  end

  def return_due
    @books_due = Book.where("created_at  <= ?", 1.month.ago).order("id DESC").page(params[:page]).per_page(10)
  end

  def show
    @book = Book.all
    @books = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    #reg_num = Book.find(params[:reg_number])
      if @book.save
        respond_to do |format|
          format.js{}
        end
      else
        respond_to do |format|
          format.js{}
        end
      end
  end

  def update
    @book = Book.find(params[:id])    
      if @book.update_attribute(:returned,true)
        redirect_to view_path
      end
  end

  private
  	def book_params
  		params.require(:book).permit(:firstname,:lastname,:phone,:reg_number,:gender,:category,:title,:author)
  	end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_error.html.erb
	
		<div class="text-danger" data-alert='alert'>
	        <a class="close" data-dismiss='alert'>close</a>
			<%= (pluralize(@book.errors.size  , "error")) %>
			<ul>
				<% @book.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
				<% end %>
			</ul>
		</div>	

		

app/views/home/_success.html.erb
<p class='text-success' id='success-text'>
	saved successfully!
</p>

app/views/home/_table_view.html.erb

		<table class='table table-bordered table-striped' id='book-table'>			
			<thead>				
				<tr>
					<td>S/N</td>
					<td>name</td>
					<td>reg number</td>
					<td>phone</td>
					<td>book category</td>
					<td>book author</td>
					<td>book title</td>	
					<td>date borrowed</td>
					<td>returned ?</td>				
				</tr>			
			</thead>		
			<tbody>	
				<% @books.each do |book| %>	
				<tr>
					<td class='book-td'><%= book.id %></td>
					<td class='book-td'><%= book.firstname.humanize %> <%= book.lastname.humanize %></td>
					<td class='book-td'><%= book.reg_number %></td>
					<td class='book-td'><%= book.phone %></td>
					<td class='book-td'><%= book.category %></td>
					<td class='book-td'><%= book.author %></td>
					<td class='book-td'><%= book.title %></td>
					<td class='book-td'><%= (book.created_at + 6.days).strftime('%d %b %Y') %></td>
					<td class='book-td'><% if book.returned == false %>
						<%= book.returned%><%= link_to '(update)',home_path(book),id:'update', method: :patch,data: {confirm: 'Are You Sure You Want To update book ?'  } %>
						<%else%>
						<%= book.returned%>
						<%end%>
					</td>
				</tr>
				<%end%>
			</tbody>					
		</table>	
		<div class='row' id='paginate-div'>
			<%= will_paginate @books ,  renderer: BootstrapPagination::Rails ,remote:true %>
		</div>

app/views/home/create.js.erb



<% if @book.errors.any? %>

$(".error").html("<%= (escape_javascript(render 'error')) %>")

<%else%>

	$(".error").html("<%= (escape_javascript(render 'success')) %>")
					
<%end%>



app/views/home/new.html.erb
<% provide(:title, 'NEW')%>
<div class='container' id='home-container'>
<div class='row'>
	<%= image_tag('header.jpg', alt:'header', class:'img-responsive',width:'100%') %>
</div>
<div class="row"> 
<nav role='navigation' class='navbar navbar-inverse'>
	
	<div class='navbar-header'>
		<button type='button' data-target='#navbarCollapse' data-toggle='collapse' class='navbar-toggle'>
			<span class='sr-only'>Toggle Navigation</span>
			<span class='icon-bar'></span>
			<span class='icon-bar'></span>
			<span class='icon-bar'></span>
			</button>
				
	</div>
	<div id='navbarCollapse' class='collapse navbar-collapse'>
		<ul class='nav nav-tabs'>
			<li class='active '><a href='#'><span class="glyphicon glyphicon-home">home</a></li>
			<li><%= link_to 'edit profile' , edit_admin_registration_path %></li>			
			<li><%= link_to 'about' %></li>
			<li></span><%= link_to 'logout', destroy_admin_session_path %></li>
		</ul>
	</div>
</nav>
</div>

<div class='row' id='body-row'>
	<div class='col-sm-10 col-md-3 col-lg-3' id='left-div'>
		  
		<table class="table table-bordered table-hover" id='nav-table'>
			<tr>
				<td>
		       		<%= link_to 'view borrowed books', view_path %>
		    	</td>
		    </tr>
		    <tr>
				<td>
		       		<%= link_to 'update book status' %>
		    	</td>
		    </tr>
		     <tr>
				<td>
		       		<%= link_to 'view books due', return_due_path %>
		    	</td>
		    </tr>
		    <tr>
				<td>
					<%= link_to 'delete request' %>
		    	</td>
		    </tr>
		</table>
		<div class='row'>
		<%= form_tag  search_path, method: :get , html:{class:'form-inline'} do  %>
			<div class="form-inputs">
				<%= text_field_tag :search , params[:search] %>
				 <span class="form-actions">
				<%= submit_tag  "Search", name:nil, class:"btn btn-default", id:'button' %>						
				</span>
				<p class='text-warning' id='empty_search'><%= empty_search %></p>
			</div>
		<%end%>
		</div>
	</div>

	<div class='col-sm-10 col-md-8 col-lg-8' id='right-div'>
		<div class="error" >
		</div>		
		<%= simple_form_for :book ,remote:true, url:home_index_path do |f| %>
			<table class='table' >
			<div class="form-inputs ">				 
				<tr>	 
					<td class='label-td'>FIRSTNAME</td>
					<td> <%= f.input :firstname, label:false, autofocus:true %></td>					
				</tr>					
				<tr>
					<td class='label-td'>LASTNAME</td>
					<td><%= f.input :lastname ,label:false %></td>
				</tr>	
				<tr>
					<td class='label-td'>REG NUMBER</td>
					<td><%= f.input :reg_number , as: :tel, input_html:{ maxlength: 11}, label:false %></td>			
				</tr>
				<tr>
					<td class='label-td'>GENDER</td>
					 <td>
					 	<%= f.collection_radio_buttons :gender,  [[true, 'Male'] ,[false, 'Female']], :first, :last %>
					 </td>	
				</tr>
				<tr>
					<td class='label-td'>PHONE</td>
					<td><%= f.input :phone , as: :tel,input_html: { maxlength: 11} ,label:false %></td>
				</tr>	
				
				<tr>
					<td class='label-td'>CATEGORY</td>
					<td>
					 	<%= f.input :category, label:false%>
					</td>
				</tr>
				<tr>	
					<td class='label-td'>AUTHOR</td>
					<td><%= f.input :author,label:false  %></td>
				</tr>
				<tr>	
					<td class='label-td'>TITLE</td>
					<td> <%= f.input :title ,label:false %></td>  					
				</tr>
			</div>
				<tr>
			 <div class="form-actions">
			 	<td>&nbsp;</td>
    			<td><%= f.button :submit, "SUBMIT"  , class:'btn btn-primary' %></td>
  			 </div>
  			 	</tr>
  			</table>
		<% end %>
	</div>
</div>
<%= pie_chart Book.group(:firstname).count %>
</div>

app/views/home/return_due.html.erb
<div class='container' id='home-container'>
	<div class='row'>
		<%= image_tag('header.jpg', alt:'header', class:'img-responsive',width:'100%') %>
	</div>
	<div class='btn-success-div'>
		<%= link_to 'GO BACK', new_home_path,class:'btn btn-default'  %>
	</div>

	<div class='row' id='book-div'>

		<table class='table table-bordered table-striped' id='book-table'>			
			<thead>				
				<tr>
					<td>S/N</td>
					<td>name</td>
					<td>reg number</td>
					<td>phone</td>
					<td>book category</td>
					<td>book author</td>
					<td>book title</td>	
					<td>date borrowed</td>
					<td>returned ?</td>				
				</tr>			
			</thead>		
			<tbody>	
				<% @books_due.each do |book| %>	
				<tr>
					<td class='book-td'><%= book.id %></td>
					<td class='book-td'><%= book.firstname.humanize %> <%= book.lastname.humanize %></td>
					<td class='book-td'><%= book.reg_number %></td>
					<td class='book-td'><%= book.phone %></td>
					<td class='book-td'><%= book.category %></td>
					<td class='book-td'><%= book.author %></td>
					<td class='book-td'><%= book.title %></td>
					<td class='book-td'><%= book.created_at.strftime('%d %b %Y') %></td>
					<td class='book-td'><% if book.returned == false %>
						<%= book.returned%><%= link_to '(update)',home_path(book),id:'update', method: :patch,data: {confirm: 'Are You Sure You Want To update book ?'  } %>
						<%else%>
						<%= book.returned%>
						<%end%>
					</td>
				</tr>
				<%end%>
			</tbody>					
		</table>	
		<div class='row' id='paginate-div'>
			<%= will_paginate @books_due ,  renderer: BootstrapPagination::Rails ,remote:true %>
		</div>
	</div>
</div>

app/views/home/search.html.erb

<% provide(:title, 'SEARCH')%>
<div class='container' id='home-container'>
<div class='row'>
	<%= image_tag('header.jpg', alt:'header', class:'img-responsive',width:'100%') %>
</div> 

<div class='row' id='book-div'>
	<p class='text-info'>
		<% if  @search_result.count.zero? %>
			oops! sorry no record found.

		<% else%>
			<%= @search_result.count %> record(s) found.
		<%end%> 
	</p>
		<table class='table table-bordered table-striped' id='book-table'>			
			<thead>				
				<tr>
					<td>S/N</td>
					<td>name</td>
					<td>reg number</td>
					<td>phone</td>
					<td>book category</td>
					<td>book author</td>
					<td>book title</td>	
					<td>date borrowed</td>
					<td>returned ?</td>				
				</tr>			
			</thead>		
			<tbody>					
			<%  @search_result.each do |search|  %>
				<tr>
					<td class='book-td'><%= search.id %></td>
					<td class='book-td'><%= search.firstname.humanize %> <%= search.lastname.humanize %></td>
					<td class='book-td'><%= search.reg_number %></td>
					<td class='book-td'><%= search.phone %></td>
					<td class='book-td'><%= search.category %></td>
					<td class='book-td'><%= search.author %></td>
					<td class='book-td'><%= search.title %></td>
					<td class='book-td'><%= search.created_at.strftime('%d %b %Y') %></td>
					<td class='book-td'>
						<% if search.returned == false %>
						<%= search.returned%><%= link_to '(update)',home_path(search), method: :patch,data: {confirm: 'Are You Sure You Want To update book ?' } %>
						<%else%>
						<%= search.returned%>
						<%end%>
					</td>
				</tr>
				<%end%>
			</tbody>					
		</table>	
		
		<%= will_paginate @search_result ,  renderer: BootstrapPagination::Rails  %>


app/views/home/search.js.erb
alert("Enter Some text")

app/views/home/view.html.erb

<% provide(:title, 'VIEW BOOKS')%>
<div class='container' id='home-container'>
	<div class='row'>
		<%= image_tag('header.jpg', alt:'header', class:'img-responsive',width:'100%') %>
	</div>
	<div class='btn-success-div'>
		<%= link_to 'GO BACK', new_home_path,class:'btn btn-default'  %>
	</div>

	<div class='row' id='book-div'>
		<%= render 'table_view' %>				
	</div>
</div>

app/views/home/view.js.erb

$("#book-div").html("<%= escape_javascript(render('home/table_view')) %>")




$(document).ready(
   function(){
	$("#book-div .pagination  a").on("click",function(e){
		$(".pagination").html('please wait...')
		$.getScript(this.href)
		e.preventDefault()
	})
})



app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= javascript_include_tag "https://www.google.com/jsapi","chartkick" %>
  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Source+Sans+Pro">
  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Dosis">
<meta name="viewport" content="width=device-width,initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  	<%= yield %>
  
</body>
</html>